services:
  backend:
    build: .
    networks:
      - dev-db-network
    ports:
      - 8080:8080
    secrets:
      - db_passwd_secret
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD_FILE=/run/secrets/db_passwd_secret
    depends_on:
      dev-db:
        condition: service_healthy

  dev-db:
    image: docker.io/library/postgres:17.6-alpine3.22
    restart: always
    shm_size: 128mb
    secrets:
      - db_passwd_secret
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd_secret
    volumes:
      - dev-db-volume:/var/lib/postgresql/data
    networks:
      - dev-db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  dev-db-network:

volumes:
  dev-db-volume:

secrets:
  db_passwd_secret:
    file: ./env/secrets/db_password.txt
