definitions:
  db.FavoriteMovie:
    properties:
      movie_id:
        type: string
      user_id:
        type: string
    type: object
  db.GetMovieByIDRow:
    properties:
      amount_rates:
        type: integer
      created_at:
        $ref: '#/definitions/pgtype.Timestamp'
      id:
        type: string
      rating:
        type: number
      title:
        type: string
    type: object
  db.GetMovieRatingListRow:
    properties:
      movie_id:
        type: string
      rating:
        $ref: '#/definitions/pgtype.Int4'
    type: object
  db.Movie:
    properties:
      created_at:
        $ref: '#/definitions/pgtype.Timestamp'
      id:
        type: string
      title:
        type: string
    type: object
  db.RatedMovie:
    properties:
      movie_id:
        type: string
      rating:
        $ref: '#/definitions/pgtype.Int4'
      user_id:
        type: string
    type: object
  db.UserDatum:
    properties:
      created_at:
        $ref: '#/definitions/pgtype.Timestamp'
      id:
        type: string
      is_admin:
        type: boolean
      login:
        type: string
      name:
        type: string
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    format: int32
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Int4:
    properties:
      int32:
        format: int32
        type: integer
      valid:
        type: boolean
    type: object
  pgtype.Timestamp:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        description: Time zone will be ignored when encoding to PostgreSQL.
        type: string
      valid:
        type: boolean
    type: object
  reqmodel.FavoriteMovieListResponse:
    properties:
      favorite_movie_ids:
        items:
          type: string
        type: array
      user_id:
        type: string
    type: object
  reqmodel.MovieListResponse:
    properties:
      movie_list:
        items:
          $ref: '#/definitions/db.Movie'
        type: array
    type: object
  reqmodel.MovieRequest:
    properties:
      title:
        type: string
    type: object
  reqmodel.RatedMovieListResponse:
    properties:
      rated_movie_list:
        items:
          $ref: '#/definitions/db.GetMovieRatingListRow'
        type: array
      user_id:
        type: string
    type: object
  reqmodel.RatedMovieRequest:
    properties:
      movie_id:
        type: string
      rating:
        $ref: '#/definitions/pgtype.Int4'
    type: object
  reqmodel.UserListResponse:
    properties:
      user_list:
        items:
          $ref: '#/definitions/db.UserDatum'
        type: array
    type: object
  reqmodel.UserRequest:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Basic swagger for current api
  termsOfService: http://swagger.io/terms/
  title: movie_backend_go
  version: "1.0"
paths:
  /movie:
    get:
      consumes:
      - application/json
      description: Get movie list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reqmodel.MovieListResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show movie list
      tags:
      - movie
    post:
      consumes:
      - application/json
      description: Create movie
      parameters:
      - description: Movie creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.MovieRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Movie'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create movie
      tags:
      - movie
  /movie/{id}:
    delete:
      consumes:
      - application/json
      description: Delete movie
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - movie
    get:
      consumes:
      - application/json
      description: Get movie by id
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetMovieByIDRow'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show movie
      tags:
      - movie
    patch:
      consumes:
      - application/json
      description: Update movie
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      - description: Movie creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.MovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Movie'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update movie
      tags:
      - movie
  /user:
    get:
      consumes:
      - application/json
      description: Get user list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reqmodel.UserListResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show user list
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: User creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.UserDatum'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Get user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.UserDatum'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show user
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.UserDatum'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update user
      tags:
      - user
  /user/{user_id}/favorite_movie:
    get:
      consumes:
      - application/json
      description: Get user favorite_movie list
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reqmodel.FavoriteMovieListResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - favorite_movie
  /user/{user_id}/favorite_movie/{movie_id}:
    delete:
      consumes:
      - application/json
      description: Delete favorite movie
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - favorite_movie
    post:
      consumes:
      - application/json
      description: Add movie to favorite
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.FavoriteMovie'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - favorite_movie
  /user/{user_id}/rated_movie:
    get:
      consumes:
      - application/json
      description: Get rated by user movie info
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reqmodel.RatedMovieListResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - rated_movie
    patch:
      consumes:
      - application/json
      description: Update movie rating
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Updated rating
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.RatedMovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.RatedMovie'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - rated_movie
    post:
      consumes:
      - application/json
      description: Rate movie
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Rate movie data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/reqmodel.RatedMovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.RatedMovie'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - rated_movie
  /user/{user_id}/rated_movie/{movie_id}:
    delete:
      consumes:
      - application/json
      description: Delete movie rating
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - rated_movie
swagger: "2.0"
